version: '3.8'

services:
  backend:
    image: ghcr.io/rtuitlab/magic-circle/backend:latest
    environment:
      MAGICCIRCLE_APP_PORT: 5000
      MAGICCIRCLE_DB_URI: root:root@/magic_circle
  circle.db:
    image: mysql
    container_name: circle.db
    restart: always
    ports: 
    - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
    volumes:
      - "./.docker/mysql/:/var/lib/mysql:rw"
